name = "DATAFEST"

[files]
TRAIN_DATA_DIR = 'data/train'
VAL_DATA_DIR = 'data/val'
EVAL_DATA_DIR = 'data/test'
LABEL_FILE = 'data/annotations.json'
CHECKPOINT = 'weights.pth'
MODEL_DIR = 'ResNet-'
OUTPUT_FILE = 'submission.csv'

[constants]
SAMPLE_RATE = 2000
RESAMPLE_RATE = 1000
LOW_PASS=750
HIGH_PASS=10
MAX_SAMPLE_NUM=49152
BATCH_SIZE = 14
CLASS_NUM = 2
lr = 1e-2
epochs = 50

[dataset]
	[dataset.train]
	mode='train'

	[dataset.val]
	mode='val'

	[dataset.eval]
	mode='eval'
