name = "DATAFEST"

[files]
TRAIN_DATA_DIR = 'data/train'
VAL_DATA_DIR = 'data/val'
EVAL_DATA_DIR = 'data/test'
LABEL_FILE = 'data/annotations.json'
CHECKPOINT = 'weights.pth'
MODEL_DIR = 'ResNet-'
OUTPUT_FILE = 'submission.csv'

[constants]
SAMPLE_RATE = 2000
RESAMPLE_RATE = 512
LOW_PASS=95
HIGH_PASS=65
Q_FACTOR = 4
MAX_SAMPLE_NUM = 16384
BATCH_SIZE = 64
lr = 1e-2
epochs = 200

[dataset]
	[dataset.train]
	mode='train'

	[dataset.val]
	mode='val'

	[dataset.eval]
	mode='eval'
